# Generated by Django 5.2.8 on 2025-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('inter', 'Inter'), ('degree', 'Degree')], default='inter', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('inter', 'Inter'), ('degree', 'Degree'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
