# Generated by Django 5.2.4 on 2025-11-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_category_notification_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='department',
            new_name='category_of_post',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='designation',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
